import './globals.css';
import './bg.css';
import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';
import ScrollToTopButton from '../../components/ScrollToTopButton';
import FloatingButton from '../../components/FloatingButton';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Navbar */}
        <Navbar />
        {/* Navbar */}
        {/* Page */}
        {children}
        {/* Page */}
        {/* Footer */}
        <Footer />
        {/* Footer */}
        {/* Floatting buttons */}
        <ScrollToTopButton />
        <FloatingButton />
        {/* Floatting buttons */}
      </body>
    </html>
  );
}